add proper read/write test case

diff --git a/run-tests b/run-tests
--- a/run-tests
+++ b/run-tests
@@ -1,5 +1,7 @@
 #/bin/sh
 
+rm -f temporary*
+
 failed=0;
 tests=0;
 
@@ -9,9 +11,11 @@ for i in $(find ./tests ! \( -type d -o \( -name '*.c' -o -name '*.o' \) \) ); d
     if $i; then
         echo $i;
     else
-        echo "failed: $i";
+        echo "failed: $i (code $?)";
         let "failed += 1";
     fi
 done
+
+rm -f temporary* 
 
 echo "$tests tests, $failed failed";
